### ISSUE TITLE
Sqflite ffi test fails if inserting a bool to a int column, but not with "normal" sqflite

### ISSUE THREAD

**Issue by davidmartos96** [tekartik/sqflite_more#16]
The following piece of code fails in the `sqflite_test_app` project.
The same code runs fine when using `sqflite` with the native code in the phone.

```dart
test('insert bool', () async {
    var db = await openDatabase(inMemoryDatabasePath);
    await db.execute('''
      CREATE TABLE boolTable (
        id INTEGER PRIMARY KEY,
        b INTEGER NOT NULL
      )''');

    final id = await db.insert(
      'boolTable',
      {'b': true},
    );
    expect(id, isNotNull);
  });
```

The same happens if the column is defined as `BOOLEAN` (https://www.sqlite.org/datatype3.html#affinity_name_examples) 

Should it be failing?

**Comment by alextekartik** [comment]
Yes it should be failing as ffi does. bool is not supported on SQLite. I tried to avoid any argument checking on the native Android/iOS but I might add some some checks in debug to avoid using types other than the supported types (including enforcing the usage of UInt8List for blobs).

Unfortunately the native Android implementation converts any argument to String so any insert might work but not as you would expect. In your example, `true` will be inserted as text which is likely not what you expect. converting a bool to int is a common usage but it has to be explicit as query should also use int and not boolean.

**Comment by davidmartos96** [comment]
I didn't know about that behavior in the platform channel sqflite. I guess is the same with iOS right?
The thing is I noticed one of my tests was failing because of this while it's been working fine in both platforms in production.
I guess I will need to track down in which places I'm using bool and make it an explicit int.
Do you think then the changes should be made in the Dart implementation of sqflite and don't allow bool params? It may be quite a breaking change though, but it will make it consistent and would avoid future bugs.
Another option could be turning the bools into ints in the Dart side before sending the args to native.

**Comment by alextekartik** [comment]
Unfortunately the behavior is inconsistent on Android and iOS (android insert bool as text and ios as int) so any change (converting to int) will be a breaking change so I'd rather ban boolean first so that nobody ends up with a table that they cannot read just by upgrading sqflite dependency.

I had no plan so far but it could be as of today...The test will only be in debug and exception will be thrown if any parameters are not of the expected type. I could just print a warning but throwing exception/assert is the best to see the issue right away.

However I think I will make in 2 steps. First just a printed warning if any param is not a num/String/Uint8List. Firestore tends to do the same to start deprecating api. The change (actually just the check) will be made in the dart side. By doing so, people hopefully will start seeing that they do something wrong. Then later (couple of months or sooner), it will throw an exception on debug and maybe even later (next major version) it might also throw an exception on release.

Or maybe you think I should throw the exception right away which could definitely help you pinpoint the issues in your code.

**Comment by davidmartos96** [comment]
I think a 2 steps approach could work: 
1. Print an error in the console (with the stacktrace so that it is noticeable with other logs)
2. Use asserts since they only work in debug or throw on release as you point out.

I think this change would be great, because the current behavior can confuse some people. In my case I actually thought `sqflite` was supporting `bool` as a param. Other Sqlite libraries do too, like `sqlite3` in Python.
When I first started using the `sqflite` library I was always turning my bools into ints, but at one point I tried using bool directly, and it worked out just fine, so I started using that instead as it was simpler... That may also have happened already to other people.

**Comment by alextekartik** [comment]
I have published version 1.2.2+1 that prints a warning (only once per type). No stack trace sorry yet.
It might no be sufficient to pinpoint where the issue is without it yet, solution being to put a breakpoint where it is printed. However everything is ready to throw an exception (I wanted to do this for a long time...)

**Comment by davidmartos96** [comment]
The suggestion for a stacktrace was only to make it noticeable, but the message you implemented is perfectly fine.
Thanks @alextekartik!

**Comment by alextekartik** [comment]
Thanks @davidmartos96 for pinpointing this issue which was on my todo list for a long time!

**Comment by klausszilvas** [comment]
i mode a small fix for the bool type. Do not know if handles all tyes, but looks ok in the moment..
sqlite_ffi_impl.dart, lines 439:
        for (var argument in sqlArguments) {
         i++;
          if (argument == null) {
          } else if (argument is num) {
          } else if (argument is String) {
          } else if (argument is bool) {
            sqlArguments[i] = argument?1:0;
           /// argument = argument?1:0;
          } else if (argument is Uint8List) {
          } else {
            throw ArgumentError(
                'Invalid sql argument type \'${argument.runtimeType}\': $argument');
          }
        }
